### PR TITLE
leveldb library added

### PR DESCRIPTION
**Pull request by JonghyeokPark**
The Leveldb library and wrapper functions are added.
The leveldb_wrapper can be applicable for other lsm-tree based storage engine.
Please see the comments in  wrappers/leveldb/CMakeLists.txt

### CODE REVIEW

**Comment by wangtzh** [comment]
It seems tests are failing - any ideas?

**Comment by JonghyeokPark** [comment]
> It seems tests are failing - any ideas?

The snappy and numa library are not prepared, 
It should check library existence first, and link those libraries to wrapper function.

**Comment by llersch** [comment]
Thanks for the contribution, I started reviewing the changes, but since there are some commits that undo initial changes, it will be confusing to read my comments.

Could you make a new Pull Request with a single commit with all changes?
Then I will make my comments on the new PR and we can work together to fix the build errors.

For the future, you can use `git commit --amend` to edit the last commit and avoid creating new ones. Keeping a single commit per Pull Request makes it easier to review :)

**Comment by JonghyeokPark** [comment]
@llersch sorry for duplicate commit request, I will make a new PR.

**Pull request closed without merging**
